---
title: "Temporal pathway: dyno validation"
output: html_notebook
---


```{r setup, include = F}
library(bnlearn)
library(iprior)
library(RColorBrewer)
library(GSVA)
library(GSEABase)
library(Seurat)
library(cluster)
library(scales)
library(reshape2)
library(dplyr)
library(gplots)
library(tibble)
library(igraph)
library(harmony)
library(readr)

plot_features <- function(graph, l, features){
  pal <- colorRampPalette(brewer.pal(5, "Reds"))
  features <- features[which(features %in% rownames(exprMatrix_bycluster))]
  for (i in 1:length(features)){
    V(graph)$color <-  pal(15)[cut(vertex_attr(edge_graph, as.character(features[[i]]), index = V(edge_graph)), breaks=15)]  
    plot(graph, layout=l, vertex.frame.color="#FFFFFF", edge.arrow.size = 0.4, edge.width = 1.5, vertex.label.family="Calibri", main = paste0(features[[i]]), edge.lty = E(edge_graph)$type)
  }
}

plot_double_features <- function(graph, l, feature1, feature2){
 pal <- colorRampPalette(brewer.pal(8, "RdBu"))
 feature1_exp <- scale(vertex_attr(edge_graph, as.character(feature1), index = V(edge_graph)), center = T, scale =T)
 feature2_exp <- scale(vertex_attr(edge_graph, as.character(feature2), index = V(edge_graph)))
 features_exp <- feature1_exp - feature2_exp
 V(graph)$color <-  pal(15)[cut(features_exp, breaks=15)]
   plot(graph, layout=l, vertex.frame.color="#FFFFFF", edge.arrow.size = 0.4, edge.width = 1.5, vertex.label.family="Arial", main = paste0(feature1, " and ", feature2, " expression"), edge.lty = E(edge_graph)$type, vertex.label.color = "black")
}


# cor.mtest <- function(mat, ...) {
#     mat <- as.matrix(mat)
#     n <- ncol(mat)
#     p.mat<- matrix(NA, n, n)
#     diag(p.mat) <- 0
#     for (i in 1:(n - 1)) {
#         for (j in (i + 1):n) {
#             tmp <- cor.test(mat[, i], mat[, j], ...)
#             p.mat[i, j] <- p.mat[j, i] <- tmp$p.value
#         }
#     }
#   colnames(p.mat) <- rownames(p.mat) <- colnames(mat)
#   p.mat
# }
```


```{r}
##load data
bm1 <- readRDS("/Volumes/Thinh/Bader_Lab/heartdev/GSVA_Temporal_tools/benchmarking/hepatoblast-differentiation_yang.rds")
bm1_data <- t(bm1$expression)
```

```{r load data} 

load("/Volumes/Thinh/Bader_Lab/heartdev/GSVA_Temporal_tools/HSMM_seurat_aligned.RData")
load("/Volumes/Thinh/Bader_Lab/heartdev/GSVA_Temporal_tools/HSMM_gsva.RData")

#save(eb1S, file="/Volumes/Thinh/Bader_Lab/heartdev/GSVA_Temporal_tools/HSMM_seurat_aligned.RData")

# timept <- sapply(colnames(eb1S@data), function(x) strsplit(x, split = "_")[[1]][2])
# eb1S <- AddMetaData(eb1S, timept, col.name = "Time")

ident_use <- "res.1.5"
#eb1S@meta.data$res.0.9 <- as.numeric(eb1S@meta.data$res.0.9) +1 

idents <- factor(eb1S@meta.data[, which(colnames(eb1S@meta.data) == ident_use)])
names(idents) <- rownames(eb1S@meta.data)
exprMatrix <- as(eb1S@data, "matrix")

ident_df <- subset(eb1S@meta.data, select=c("orig.ident", ident_use))
#ident_df <- column_to_rownames(inner_join(ident_df, clusters[, c(1, 2)], by = "V1"), var = "V1")
colnames(ident_df)[2] <- "cluster"
colnames(ident_df)[1] <- "orig.ident"

timepts <- unique(ident_df$orig.ident)
percent_cl <- list()
for (i in 1:nrow(ident_df)){
  percent_cl[[i]] <- length(ident_df$cluster[which(ident_df$orig.ident == ident_df$orig.ident[[i]] & ident_df$cluster == ident_df$cluster[[i]])])/
    length(ident_df$cluster[which(ident_df$cluster == ident_df$cluster[[i]])])
}
percent_cl <- unlist(percent_cl)
ident_df$Percent <- percent_cl


cluster_info_df <- unique(ident_df)
rownames(cluster_info_df) <- NULL
cluster_info_df <- dcast(cluster_info_df, cluster~orig.ident)
cluster_info_df[is.na(cluster_info_df) ] <- 0
colnames(cluster_info_df)[1] <- "cluster"

cluster_info_df <- cluster_info_df[, c(1, order(parse_number(colnames(cluster_info_df)[2:ncol(cluster_info_df)]))+1)]

time_scale <- seq(1:(ncol(cluster_info_df)-1))
cluster_score <- apply(as.matrix(cluster_info_df[, 2:ncol(cluster_info_df)]), 1, function(x) sum(mapply(function(t, y) t*y, as.numeric(x), time_scale)))
names(cluster_score) <- cluster_info_df$cluster
```
 
```{r calculate centroid expression}
exprMatrix_df <- as.data.frame(exprMatrix)
exprMatrix_bycluster <- list()
for (i in sort(as.numeric(levels(idents)))){
  print(i)
  exprMatrix_bycluster[[i]] <- rowMeans(exprMatrix[, which(colnames(exprMatrix) %in% names(idents)[which(idents == i)])])
  #exprMatrix_bycluster_sum[[i]] <- mean(colSums(exprMatrix[, which(colnames(exprMatrix) %in% names(idents)[which(idents == i)])]))
}

exprMatrix_bycluster <- do.call(cbind, exprMatrix_bycluster)
colnames(exprMatrix_bycluster) <- sort(as.numeric(levels(idents)))
rownames(exprMatrix_bycluster) <- rownames(exprMatrix)
exprMatrix_bycluster <- as.data.frame(exprMatrix_bycluster)
```

```{r ARACNe by gene input}

exprMatrix_bycluster_pca <- prcomp(t(exprMatrix_bycluster))
screeplot(exprMatrix_bycluster_pca, npcs=25, type="lines", main="PCA on gene data")
significant_genes <- c()
hsmm_pca <- significant_genes_list <- list()
for (i in 1:4){
  genes_scaled <- scale(exprMatrix_bycluster_pca$rotation[,i])
  significant_genes <- c(names(which(genes_scaled[,1] > 2.5 | genes_scaled[,1] < -2.5)), significant_genes)
  significant_genes_list[[i]] <- exprMatrix_bycluster[which(rownames(exprMatrix_bycluster) %in% names(which(genes_scaled[,1] > 1.5 | genes_scaled[,1] < -1.5))), ]
  hsmm_pca[[i]] <- colMeans(significant_genes_list[[i]])
  #significant_pvals[[i]] <- rescale(d4_gsva_pca$rotation[,i][which(genes_scaled[,1] > 1.5 | genes_scaled[,1] < -1.5)], to=c(0, 0.05))
  #pc_cor[[i]] <- cor(t(d4_gsva_m[which(rownames(d4_gsva_m) %in% significant_pathways[[i]]), ]))
}

hsmm_pca <- Reduce(rbind, hsmm_pca)
rownames(hsmm_pca) <- paste0("PC", seq(1:nrow(hsmm_pca)))

aracne_gene <- aracne(as.data.frame(hsmm_pca))
# 
# aracne_gene <- minet::aracne(build.mim(as.data.frame(hsmm_pca)), eps=10)
# aracne_gene[which(aracne_gene < 1)] <- 0
```

```{r GSVA and ARACNe on genes}
#pathways <- getGmt("/Volumes/Thinh/Bader_Lab/heartdev/GSVA_Temporal_tools/Mouse_GOBP_AllPathways_no_GO_iea_February_01_2019_symbol.gmt")
pathways <- getGmt("/Volumes/Thinh/Bader_Lab/heartdev/GSVA_Temporal_tools/Human_GO_AllPathways_no_GO_iea_September_01_2018_symbol.gmt")


gsva_bycluster <- gsva(as.matrix(exprMatrix_bycluster), pathways, method="gsva", min.sz=5, max.sz=400, parallel.sz=detectCores()-2)

colnames(gsva_bycluster) <- colnames(exprMatrix_bycluster)
gsva_bycluster_pca <- prcomp(t(gsva_bycluster), scale = T, center = T)
screeplot(gsva_bycluster_pca, npcs=25, type="lines", main="PCA on GSVA data")

significant_pathways_list <- aligned_gsva_pca <- list()
significant_pathways <- c()
for (i in 1:4){
  genes_scaled <- scale(gsva_bycluster_pca$rotation[,i])
  significant_pathways <- c(names(which(genes_scaled[,1] > 1.5 | genes_scaled[,1] < -1.5)), significant_pathways)
  # significant_pathways_list[[i]] <- gsva_bycluster[which(rownames(gsva_bycluster) %in% names(which(genes_scaled[,1] > quantile(genes_scaled[,1], 0.95) | genes_scaled[,1] < quantile(genes_scaled[,1], 0.05)))), ]
  significant_pathways_list[[i]] <- gsva_bycluster[which(rownames(gsva_bycluster) %in% names(which(genes_scaled[,1] > 1.5 | genes_scaled[,1] < -1.5))), ]
  aligned_gsva_pca[[i]] <- colMeans(significant_pathways_list[[i]])
  #significant_pvals[[i]] <- rescale(d4_gsva_pca$rotation[,i][which(genes_scaled[,1] > 1.5 | genes_scaled[,1] < -1.5)], to=c(0, 0.05))
  #pc_cor[[i]] <- cor(t(d4_gsva_m[which(rownames(d4_gsva_m) %in% significant_pathways[[i]]), ]))
}

aligned_gsva_pca <- Reduce(rbind, aligned_gsva_pca)
rownames(aligned_gsva_pca) <- paste0("PC", seq(1:nrow(aligned_gsva_pca)))
#blacklist <- data.frame(from=names(cluster_score)[which(cluster_score == min(cluster_score))], to=names(cluster_score)[which(cluster_score == max(cluster_score))])

aracne_cluster <- aracne(as.data.frame(aligned_gsva_pca))

```


```{r filter edges}
edges_df <- as.data.frame(aracne_gene$arcs)
edges_df$to <- as.numeric(as.character(edges_df$to))
edges_df$from <- as.numeric(as.character(edges_df$from))
edges_df$from_clusterscore <- unlist(sapply(edges_df$from, function(x) cluster_score[which(names(cluster_score) == x)]))
edges_df$to_clusterscore <- unlist(sapply(edges_df$to, function(x) cluster_score[which(names(cluster_score) == x)]))

edges_df$direction <- ifelse(abs(edges_df$to_clusterscore - edges_df$from_clusterscore) < 0.6, "bidirectional", "unidirectional")
edges_df <- edges_df[-which(edges_df$from_clusterscore > edges_df$to_clusterscore), ]
edges_df$id <- ifelse(as.numeric(edges_df$from) > as.numeric(edges_df$to), paste0(edges_df$from, edges_df$to), paste0(edges_df$to, edges_df$from))
edges_df <- edges_df[!duplicated(edges_df$id), ]
edges_df <- edges_df[, -6]
edges_df$type <-  ifelse(edges_df$direction == "bidirectional", 3, 1)


```


```{r visualize}
cluster_info_df_n <- cluster_info_df
cluster_info_df_n$cluster <- as.character(cluster_info_df_n$cluster)
# cluster_info_df_n$label <- paste(seq(1:5), c("Fibroblasts", "Myotubes","Myoblasts",  "Undifferentiated", "Intermediates"), sep="-")
#cluster_info_df_n$label <- c("Fibroblasts", "Myotubes","Myoblasts",  "Undifferentiated", "Intermediates")

cluster_info_df_n$label <- paste(seq(1:5), c("Myoblasts", 
                             "Fibroblasts", 
                             "Myotubes",
                             "Undifferentiated",
                             "Intermediates"), sep="-")


cluster_info_df_n <- inner_join(cluster_info_df_n, rownames_to_column(as.data.frame(t(exprMatrix_bycluster[which(rownames(exprMatrix_bycluster) %in% c("PDGFRA", "CDK1", "MYOD1", "SPHK1", "MYOG", "MYRF", "MEF2C", "MYH2", "MYF5", "ENO3")), ])), var="cluster"))
cluster_info_df_n <- inner_join(cluster_info_df_n, rownames_to_column(as.data.frame(gsva_bycluster[grep("^REGULATION OF FIBROBLAST GROWTH FACTOR RECEPTOR SIGNALING PATHWAY", rownames(gsva_bycluster)), ]), var="cluster"))
colnames(cluster_info_df_n)[ncol(cluster_info_df_n)] <- "REGULATION OF FIBROBLAST GROWTH FACTOR RECEPTOR SIGNALING PATHWAY"
edge_graph <- graph_from_data_frame(d=edges_df, vertices = cluster_info_df_n, directed = T)
l <- layout_with_sugiyama(edge_graph)

l$layout[,2] <- 3-(rescale(cluster_score, to=c(0,3)))
l$layout[1,1] <- 0.5
#l$layout[3,1] <- 1.5
# l$layout[5,1] <- 2.0

cluster_size <- rescale(as.numeric(table(ident_df$cluster)), to=c(8,25))
names(cluster_size) <- seq(1:length(cluster_size))

cluster_label <- c("Fibroblasts", "Myotubes","Myoblasts",  "Undifferentiated", "Intermediates")
cluster_label <- c("Myoblasts", "Fibroblasts", "Myotubes", "Undifferentiated",
                             "Intermediates") #unaligned
names(cluster_label) <- seq(1:5)

if (length(levels(eb1S@meta.data$orig.ident)) > 9){
  colours <- colorRampPalette(brewer.pal(7, "YlOrRd"))
  plot(edge_graph,  layout = l$layout, vertex.shape = "pie", vertex.pie = lapply(1:nrow(cluster_info_df_n), function(x) as.numeric(cluster_info_df_n[x,2:(length(levels(eb1S@meta.data$orig.ident))+1)])), 
     vertex.pie.color=list(colours(length(levels(eb1S@meta.data$orig.ident)))), pie.border=list(rep("white", 4)), vertex.frame.color="white", edge.arrow.size = 0.4, edge.width = 1.5, vertex.label.family="Arial", vertex.label.color="black", edge.lty = E(edge_graph)$type, vertex.label.cex=1.5)
} else {
  colours <- brewer.pal(length(levels(eb1S@meta.data$orig.ident)), "YlOrRd")
  plot(edge_graph,layout = l$layout, vertex.shape = "pie", vertex.pie = lapply(1:nrow(cluster_info_df_n), function(x) as.numeric(cluster_info_df_n[x,2:(length(levels(eb1S@meta.data$orig.ident))+1)])), 
     vertex.pie.color=list(colours), pie.border=list(rep("white", length(levels(eb1S@meta.data$orig.ident)))), vertex.frame.color="white", edge.arrow.size = 0.4, edge.width = 1.5, vertex.label.family="Arial", vertex.label.color="black", edge.lty = E(edge_graph)$type, vertex.label.cex=1.5, vertex.size = 21)
}





l_nicely <- layout_nicely(edge_graph)
plot_features(edge_graph, l$layout, c("PDGFRA", "CDK1", "MYOD1", "SPHK1", "MYOG", "MYRF", "MEF2C", "MYH2", "MYF5", "ENO3"))

library(autoimage)
legend.scale(c(-1, 1), col = brewer.pal(9, "Reds"), horizontal = FALSE, axis.args = list(at=c(-1, 1), tick = T))

plot_double_features(edge_graph, l$layout, "CDK1", "MYOG")

cluster_markers <- FindAllMarkers(eb1S, only.pos = T)
cluster_markers <- cluster_markers[which(cluster_markers$p_val_adj < 0.05), ]


```



```{r}
adj_ours_aligned <- 2
f1_ours_aligned <- 0.7


eb1S <- SetAllIdent(eb1S, "orig.ident")
all_data_a <- SetAllIdent(all_data_a, "orig.ident")

tsne_coord_u <- eb1S@dr$tsne@cell.embeddings
tsne_pal <- hue_pal()(length(unique(eb1S@ident)))

tsne_coord_a <- all_data_a@dr$tsne@cell.embeddings
tsne_pal_a <- hue_pal()(length(unique(all_data_a@ident)))

par(mfrow=c(2,3), mar=c(3,3,3,1), mgp=c(0.5,0,0))

plot(tsne_coord_a, col=alpha(tsne_pal_a[all_data_a@ident],.7), pch=20, xaxt="n", yaxt="n", xlab = "tSNE_1", ylab="tSNE_2", bty="l", main = "HSMM data with alignment")
legend("bottomright", legend=c("T0", "T24", "T48", "T72"), col=tsne_pal, pch=20, horiz = F, bty="n")
legend("topleft", legend=" ", title= expression(bold("a")),
       bty='n', inset = c(-0.15, -.09), xpd=T)
plot(tsne_coord_u, col=alpha(tsne_pal[eb1S@ident],.7), pch=20, xaxt="n", yaxt="n", xlab = "tSNE_1", ylab="tSNE_2", bty="l", main = "HSMM data without alignment")
legend("topleft", legend=" ", title= expression(bold("b")),
       bty='n', inset = c(-0.15, -.09), xpd=T)


eb1S <- SetAllIdent(eb1S, "res.1.5")
tsne_pal <- hue_pal()(length(unique(eb1S@ident)))

plot(tsne_coord_u, col=alpha(tsne_pal[eb1S@ident],.7), pch=20, xaxt="n", yaxt="n", xlab = "tSNE_1", ylab="tSNE_2", bty="l", main = "Clusters in HSMM data without alignment")
text(x=tapply(FUN=mean,X=eb1S@dr$tsne@cell.embeddings[,1],
              INDEX=eb1S@ident),
     y=tapply(FUN=mean,X=eb1S@dr$tsne@cell.embeddings[,2],
              INDEX=eb1S@ident),
     labels=seq(1:length(unique(eb1S@ident))),font=2)
legend("topleft", legend=" ", title= expression(bold("c")),
       bty='n', inset = c(-0.15, -.09), xpd=T)

plot(edge_graph,layout = l$layout, vertex.shape = "pie", vertex.pie = lapply(1:nrow(cluster_info_df_n), function(x) as.numeric(cluster_info_df_n[x,2:(length(unique(eb1S@meta.data$orig.ident))+1)])), 
     vertex.pie.color=list(colours), pie.border=list(rep("white", length(unique(eb1S@meta.data$orig.ident)))), vertex.frame.color="white", edge.arrow.size = 0.2, edge.width = 1.5, vertex.label.family="Arial", vertex.label.color="black", edge.lty = E(edge_graph)$type, vertex.label.cex=1.5, main = "Tempo trajectory in HSMM data without alignment")
legend("topleft", legend=" ", title= expression(bold("d")),
       bty='n', inset = c(-0.15, -.1), xpd=T)

par(mgp=c(2,1,0))
barplot(c(adj_ours_aligned, adj_ours_unaligned), names.arg = c("Tempo", "Tempo without alignment"), main = "Graph edit distance", col="lightblue", ylab="Lineage quality score (GED)", cex.names = 1.3, border = "lightblue",  bty="l", cex.axis = 1.1)
legend("topleft", legend=" ", title= expression(bold("e")),
       bty='n', inset = c(-0.15, -.09), xpd=T)
barplot(c(f1_ours_aligned, f1_ours_unaligned), names.arg = c("Tempo", "Tempo without alignment"), main = "F1 score", col="lightblue", ylim = c(0,1), ylab = "Lineage quality score (F1)", cex.names = 1.3, border = "lightblue", bty="l", cex.axis = 1.1)
```




```{r}

corrplot(cor(exprMatrix_bycluster), type="upper", order="hclust", p.mat = cor.mtest(exprMatrix_bycluster), sig.level = 0.01, insig = "blank")

corrplot(cor(gsva_bycluster), type="upper", order="hclust", p.mat = cor.mtest(gsva_bycluster), sig.level = 0.01, insig = "blank")

library(lineup)
cluster3 <- rownames(eb1S@meta.data)[which(eb1S@meta.data$res.1.5 == 3)]
cluster4 <- rownames(eb1S@meta.data)[which(eb1S@meta.data$res.1.5 == 4)]
cluster1 <- rownames(eb1S@meta.data)[which(eb1S@meta.data$res.1.5 == 1)]

cl3vs1_gene <- corbetw2mat(
exprMatrix[, which(colnames(exprMatrix) %in% cluster3)], exprMatrix[, which(colnames(exprMatrix) %in% cluster1)], what="all")
cl3vs1_gene[upper.tri(cl3vs1_gene, diag = T)] <- ""
cl3vs1_gene_lower <-  c(as.matrix(cl3vs1_gene))
  
cl3vs1_pw <- corbetw2mat(aligned_gsva[, which(colnames(aligned_gsva) %in% cluster3)], aligned_gsva[, which(colnames(aligned_gsva) %in% cluster1)], what="all")
cl3vs1_pw[upper.tri(cl3vs1_pw, diag = T)] <-""
cl3vs1_pw_lower <-  c(as.matrix(cl3vs1_pw))
  

plot(y=cl3vs1_gene_lower, x=cl3vs1_pw_lower, xlab="Pathway cell-cell correlation", ylab="Gene cell-cell correlation", main="Cluster 3 (myoblasts) & cluster 1 (fibroblasts) cell to cell correlation", ylim=c(0,1), xlim=c(-0.2, 1))

cl4vs1_gene <- corbetw2mat(
exprMatrix[, which(colnames(exprMatrix) %in% cluster4)], exprMatrix[, which(colnames(exprMatrix) %in% cluster1)], what="all")
cl4vs1_gene[upper.tri(cl4vs1_gene, diag = T)] <- ""
cl4vs1_gene_lower <-  c(as.matrix(cl4vs1_gene))

cl4vs1_pw <- corbetw2mat(aligned_gsva[, which(colnames(aligned_gsva) %in% cluster4)], aligned_gsva[, which(colnames(aligned_gsva) %in% cluster1)], what="all")
cl4vs1_pw[upper.tri(cl4vs1_pw, diag = T)] <-""
cl4vs1_pw_lower <-  c(as.matrix(cl4vs1_pw))

plot(y=cl4vs1_gene_lower, x=cl4vs1_pw_lower, xlab="Pathway cell-cell correlation", ylab="Gene cell-cell correlation", main="Cluster 4 (undifferentiated cells) & cluster 1 (fibroblasts) cell to cell correlation", xlim=c(-0.2, 1), ylim=c(0,1))

exprMatrix_write <- rownames_to_column(as.data.frame(exprMatrix), var="Gene")
exprMatrix_write$Annotation <- exprMatrix_write$Gene
exprMatrix_write <- exprMatrix_write[, c(1, 273, 2:272)]
write.table(exprMatrix_write, file="~/Desktop/hsmm_exprMatrix.txt", quote=F, sep="\t", row.names = F)
```


```{r}
source("/Volumes/Thinh/Bader_Lab/Helper/colorRampPaletteAlpha.R")
col1 <- addalpha("grey81", 0.5)
col2 <- addalpha("orange", 0.5)
col3 <- addalpha("red", 0.5)
colors <- c(col1, col2, col3)
palette <- colorRampPaletteAlpha(colors, 100)
tsne_pal <- hue_pal()(length(unique(eb1S@ident)))


par(mfrow=c(3,3), mar=c(3,3,2,1), mgp=c(0.5,0,0))

tsne_coord <- eb1S@dr$tsne@cell.embeddings
plot(tsne_coord, col=alpha(tsne_pal[eb1S@ident],.7), pch=20, xaxt="n", yaxt="n", xlab = "tSNE_1", ylab="tSNE_2")
text(x=tapply(FUN=mean,X=eb1S@dr$tsne@cell.embeddings[,1],
              INDEX=eb1S@ident),
     y=tapply(FUN=mean,X=eb1S@dr$tsne@cell.embeddings[,2],
              INDEX=eb1S@ident),
     labels=seq(1:5),font=2)

# for (i in c('CDK1', 'MYOD1', 'MYOG', 'SPHK1')){
#   markers <- i ####input gene symbol here
#   index <- rownames(exprMatrix) %in% markers
#   cmgene <- cut(cbind(exprMatrix[index,]),breaks=100,labels=F)
#   plot(tsne_coord,col=palette[cmgene],pch=20, main = paste(markers), xaxt="n", yaxt="n", xlab = "tSNE_1", ylab="tSNE_2")
# }


if (length(levels(eb1S@meta.data$orig.ident)) > 9){
  colours <- colorRampPalette(brewer.pal(7, "YlOrRd"))
  plot(edge_graph,  layout = l$layout, vertex.shape = "pie", vertex.pie = lapply(1:nrow(cluster_info_df_n), function(x) as.numeric(cluster_info_df_n[x,2:(length(levels(eb1S@meta.data$orig.ident))+1)])), 
       vertex.pie.color=list(colours(length(levels(eb1S@meta.data$orig.ident)))), pie.border=list(rep("white", 4)), vertex.frame.color="white", edge.arrow.size = 0.4, edge.width = 1.5, vertex.label.family="Calibri", vertex.label.color="black", edge.lty = E(edge_graph)$type)
} else {
  colours <- brewer.pal(length(levels(eb1S@meta.data$orig.ident)), "YlOrRd")
  plot(edge_graph,layout = l$layout, vertex.shape = "pie", vertex.pie = lapply(1:nrow(cluster_info_df_n), function(x) as.numeric(cluster_info_df_n[x,2:(length(levels(eb1S@meta.data$orig.ident))+1)])), 
       vertex.pie.color=list(colours), pie.border=list(rep("white", length(levels(eb1S@meta.data$orig.ident)))), vertex.frame.color="white", edge.arrow.size = 0.4, edge.width = 1.5, vertex.label.family="Calibri", vertex.label.color="black", edge.lty = E(edge_graph)$type)
}

plot_features(edge_graph, l$layout, c('CDK1', 'MYOD1', 'MYOG', 'SPHK1'))

themes_to_plot <- c("NODAL SIGNALING PATHWAY", "CENTROSOME DUPLICATION", "EXTRACELLULAR MATRIX ORGANIZATION")

themes <- all
sig_pathways_theme <- sig_pvals <-  c()
for (i in 1:length(themes)){
  #print(i)
 if (length(grep(themes[i], rownames(gsva_bycluster))) > 1){
    plot_df <- data.frame(cluster=names(colMeans(aligned_gsva[grep(themes[i], rownames(aligned_gsva)), ])), value=colMeans(aligned_gsva[grep(themes[i], rownames(aligned_gsva)), ]))
    cluster_score_df <- data.frame(cluster = rownames(ident_df), time = ident_df$cell_tempscore, color = ident_df$color)
  plot_df <- full_join(cluster_score_df, plot_df, by = "cluster")
  temp_gam <- mgcv::gam(value ~ s(time, k=3, bs='cr'), data=plot_df)
  temp_anova <- anova.gam(temp_gam)
  #if (temp_anova$s.pv*length(themes_t) < 0.05){
    sig_pathways_theme <- c(sig_pathways_theme, themes[[i]])
    sig_pvals <- c(sig_pvals, temp_anova$s.pv*length(themes))
    #png(file=paste0(filepath, themes[[i]], ".png"), width=645, height = 645, res=100)
    ymin <- min(plot_df$value) - 0.1
    ymax <- max(plot_df$value) + 0.2
    plot.gam(temp_gam, main = paste0(themes[i]), xlab = "Time", ylab="Pathway expression level", bty="l", cex.main = 1, xaxt = "n", ylim=c(ymin, ymax))
  axis(side = 1, at = c(1.7, 12), labels = c("Early", "Late"), tick = F)
  points(x=plot_df$time, y=plot_df$value, pch=20, col=ident_df$color, cex=0.9)
  #text(x=plot_df[, 2], y=plot_df[,3], labels=plot_df[,1], pos = 4, cex = 1, col="navy")
    # legend("topright", legend = "Cluster", pch = 20, col = "navy", bty="n", text.col="navy", cex=0.9)
    legend("topright", legend=paste0("Adjusted p-value = ", round(temp_anova$s.pv*length(themes_t), 5)), bty="n", cex=0.9)
    #dev.off()
  }
 #}
}







keepunique <-  function(previousones, x){
    if(any(adist(x, previousones) < 20)){
        x <- NULL
    }
    return(c(previousones, x))
}

#Plot changing pathways
pca_pathways <- lapply(significant_pathways_list, function(x) sub("%.*", "", rownames(x)))
pca_pathways_cleaned <- lapply(pca_pathways, function(x) lapply(x, function(y) gsub("\\.|_", " ", y)))
allthemes <- unlist(pca_pathways_cleaned, recursive = T)

# 
themes <- Reduce(keepunique, pca_pathways_all)
themes_t <- unlist(pca_pathways_cleaned, recursive = T)
themes <- gsub("\\/", "-", themes)

themes <- pca_pathways_cleaned

themes <- c("NOTCH SIGNALING PATHWAY")

ident_df$score <- seq(1:4)[as.factor(parse_number(ident_df$orig.ident))]
ident_df$cluster_score <-  unlist(sapply(ident_df$cluster, function(x) cluster_score[which(names(cluster_score) == x)]))
ident_df$cell_tempscore <- ident_df$score*ident_df$cluster_score
ident_df$color <- as.character(tsne_pal[ident_df$cluster])

themes <- grep("SIGNAL", pca_pathways_all, value=T)

sig_pathways_theme <- sig_pvals <-  c()
for (i in 1:length(themes)){
  print(i)
 if (length(grep(themes[i], rownames(gsva_bycluster))) > 1){
    plot_df <- data.frame(cluster=names(colMeans(aligned_gsva[grep(themes[i], rownames(aligned_gsva)), ])), value=colMeans(aligned_gsva[grep(themes[i], rownames(aligned_gsva)), ]))
    cluster_score_df <- data.frame(cluster = rownames(ident_df), time = ident_df$cell_tempscore, color = ident_df$color)
  plot_df <- full_join(cluster_score_df, plot_df, by = "cluster")
  temp_gam <- mgcv::gam(value ~ s(time, k=3, bs='cr'), data=plot_df)
  temp_anova <- anova.gam(temp_gam)
  if (temp_anova$s.pv*length(allthemes) < 0.05){
    sig_pathways_theme <- c(sig_pathways_theme, themes[[i]])
    sig_pvals <- c(sig_pvals, temp_anova$s.pv*length(themes))
    #png(file=paste0(filepath, themes[[i]], ".png"), width=645, height = 645, res=100)
    ymin <- min(plot_df$value) - 0.1
    ymax <- max(plot_df$value) + 0.2
    par(mar=c(5.1, 4.1, 4.1, 8.1), xpd=TRUE)
    plot.gam(temp_gam, main = "NOTCH SIGNALING PATHWAY", xlab = "Time", ylab="Pathway expression level", bty="l", cex.main = 1, xaxt = "n", ylim=c(ymin, ymax))
  axis(side = 1, at = c(1.7, 12), labels = c("Early", "Late"), tick = F)
  points(x=plot_df$time, y=plot_df$value, pch=20, col=ident_df$color, cex=0.9)
  #text(x=plot_df[, 2], y=plot_df[,3], labels=plot_df[,1], pos = 4, cex = 1, col="navy")
    legend("topright", inset=c(-0.25, 0.1), legend = c("Neurons", "Young neurons", "APs/RPs", "IPs", "APs/RPs", "Young neurons", "IPs"), pch = 20, col = tsne_pal, bty="n", text.col="black", cex=0.9)
    legend("topright", inset=c(-0.3, 0), legend=paste0("Adjusted p-value = ", round(temp_anova$s.pv*length(allthemes), 5)), bty="n", cex=0.9)
    #dev.off()
  }
 }
}


features <- "REGULATION OF FIBROBLAST GROWTH FACTOR RECEPTOR SIGNALING PATHWAY"
 pal <- colorRampPalette(brewer.pal(5, "Reds"))
  features <- features[which(features %in% rownames(gsva_bycluster))]
  for (i in 1:length(features)){
    V(edge_graph)$color <-  pal(15)[cut(vertex_attr(edge_graph, as.character(features[[i]])), breaks=15)]  
    plot(edge_graph, layout=l$layout, vertex.frame.color="#FFFFFF", edge.arrow.size = 0.4, edge.width = 1.5, vertex.label.family="Calibri", main = "FIBROBLAST GROWTH FACTOR RECEPTOR SIGNALING PATHWAY", edge.lty = E(edge_graph)$type)
}

```


```{r Validation}
models <- data.frame(from=c("Myoblasts", "Myoblasts", "Intermediates", "Intermediates"), to=c("Intermediates", "Fibroblasts", "Undifferentiated", "Myotubes"))
vertices_list <- c("Myoblasts", "Intermediates", "Undifferentiated", "Myotubes", "Fibroblasts")


model_graph <- graph_from_data_frame(models,  vertices=vertices_list)
model_layout <- layout_with_sugiyama(model_graph)
plot(model_graph, layout = model_layout$layout, vertex.label.family="Calibri", vertex.color = "lightblue", vertex.frame.color="white", vertex.label.color="black", main="Myoblast differentiation trajectory")

edges_df$from_label <- unlist(sapply(edges_df$from, function(x) cluster_label[which(names(cluster_label) == x)]))
edges_df$to_label <- unlist(sapply(edges_df$to, function(x) cluster_label[which(names(cluster_label) == x)]))

edges_model_df <- edges_df[, c(7, 8)]
colnames(edges_model_df) <- c("from", "to")

model_edge_graph <- graph_from_data_frame(edges_model_df, vertices = vertices_list)
model_edge_layout <- layout_with_sugiyama(model_edge_graph)

par(oma=c(2,2,0,4),mar=c(3,3,2,0),mfrow=c(1,3))
  plot(model_edge_graph, layout = model_edge_layout$layout, vertex.label.family="Calibri", vertex.color = "lightblue",vertex.frame.color="white", vertex.label.color="black", main = "Tempo lineage", edge.arrow.size=0.4)
plot(monocle_model_graph, layout = mm_layout$layout, vertex.label.family="Calibri", vertex.color = "lightblue",vertex.frame.color="white", vertex.label.color="black", main = "Monocle lineage", edge.arrow.size=0.4)
plot(tscan_graph, layout = ts_layout$layout, vertex.label.family="Calibri", vertex.color = "lightblue",vertex.frame.color="white", vertex.label.color="black", main = "TSCAN lineage", edge.arrow.size=0.4)


monocle_model <- data.frame(from=rep("Myoblasts", 3), to=c("Fibroblasts", "Undifferentiated", "Myotubes"))
monocle_model_graph <- graph_from_data_frame(monocle_model, vertices = vertices_list)
mm_layout <- layout_with_sugiyama(monocle_model_graph)
plot(monocle_model_graph, layout = mm_layout$layout, vertex.label.family="Calibri", vertex.color = "lightblue",vertex.frame.color="white", vertex.label.color="black")

tscan_model <- data.frame(from=rep("Myoblasts", 2),to=c("Myotubes", "Undifferentiated"))
tscan_graph <- graph_from_data_frame(tscan_model, vertices = vertices_list)
ts_layout <- layout_with_sugiyama(tscan_graph)
plot(tscan_graph, layout = ts_layout$layout, vertex.label.family="Calibri", vertex.color = "lightblue",vertex.frame.color="white", vertex.label.color="black")

 add_id <- function(edgelist){
  edgelist$id <- ifelse(as.character(edgelist$V1) > as.character(edgelist$V2), paste0(edgelist$V1, edgelist$V2), paste0(edgelist$V2, edgelist$V1))
  return(edgelist)
}

f1_calc <- function(model, predicted){
  model_edges <- add_id(as.data.frame(as_edgelist(model)))
  predicted_edges <- add_id(as.data.frame(as_edgelist(predicted)))
  tp_d <- length(intersect(model_edges$id, predicted_edges$id))
  fn_d <- length(setdiff(model_edges$id, predicted_edges$id))
  fp_d <- length(setdiff(predicted_edges$id, model_edges$id))
  f1_d <- (2*tp_d)/(2*tp_d+fp_d+fn_d)
  return(f1_d)
}

adj_calc <- function(model, predicted){
  vertex_gap <- length(which(igraph::degree(predicted) == 0))
  return(vertex_gap + sum(get.adjacency(model) != get.adjacency(predicted)))
}

f1_ours_unaligned <- f1_calc(model_graph, model_edge_graph)
f1_monocle <- f1_calc(model_graph, monocle_model_graph)
f1_tscan <- f1_calc(model_graph, tscan_graph)
f1_ours_gene <- f1_calc(model_graph, model_edge_graph_gene)

adj_tscan <- adj_calc(model_graph, tscan_graph)
adj_ours <- adj_calc(model_graph, model_edge_graph)
adj_monocle <- adj_calc(model_graph, monocle_model_graph)
adj_ours_gene <- adj_calc(model_graph, model_edge_graph_gene)

barplot(c(f1_ours, f1_monocle, f1_tscan), names.arg = c("Tempo", "Monocle2", "TSCAN"), angle = 45, main = "F1 score", col="lightblue", ylim = c(0,1), ylab = "F1 score", cex.names = 0.9)
barplot(c(adj_ours, adj_monocle, adj_tscan), names.arg = c("Tempo", "Monocle2", "TSCAN"), angle = 45, main = "Graph edit distance", col="lightblue", ylab="Edit distance", cex.names = 0.9)
```



```{r}
library(monocle)

monocle_plot <- plot_cell_trajectory(hsmm_clust, color_by = 'Hours')
monocle_plot <- monocle_plot + ggtitle("Monocle 2 trajectory")

save(hsmm_clust, file="/Volumes/Thinh/Bader_Lab/heartdev/GSVA_Temporal_tools/hsmm_monocle.RData")

library(TSCAN)
#hsmm_preprocess <- preprocess(exprMatrix, pseudocount = 1, minexpr_percent = 0.3, minexpr_value = 0.5, logbase = 2)
hsmm_preprocess <- preprocess(exprMatrix, pseudocount = 1, minexpr_percent = 0.5, minexpr_value = 0.1, logbase = 2)

hsmm_clust_tscan <- exprmclust(hsmm_preprocess)
tscan_plot <- plotmclust(hsmm_clust_tscan, show_cell_names = F)
tscan_plot$layers <- tscan_plot$layers[c(2,3)]
tscan_plot <- tscan_plot + geom_point(aes(colour = hsmm_clust@phenoData@data$orig.ident)) + labs(color='Time point') 
tscan_plot$layers <- tscan_plot$layers[c(3,2,1)]

tscan_plot <- tscan_plot + xlab("Component 1") + ylab("Component 2") + theme(axis.title.x = element_text(size=14), axis.title.y = element_text(size=14), legend.text=element_text(size=12), legend.title = element_text(size=12), axis.text.x = element_text(size=12), axis.text.y = element_text(size=12), legend.position = "none") + ggtitle("TSCAN trajectory")

par(mfrow=c(1,2))
barplot(c(f1_ours, f1_monocle, f1_tscan), names.arg = c("Tempo", "Monocle2", "TSCAN"), angle = 45, main = "F1 score", col="lightblue", ylim = c(0,1), ylab = "F1 score")
barplot(c(adj_ours, adj_monocle, adj_tscan), names.arg = c("Tempo", "Monocle2", "TSCAN"), angle = 45, main = "Graph edit distance", col="lightblue", ylab="Edit distance")

eval_stat <- data.frame(Method= c("Tempo", "Monocle2", "TSCAN"), F1=c(f1_ours, f1_monocle, f1_tscan), GED=c(adj_ours, adj_monocle, adj_tscan))

f1_plot <- ggplot(eval_stat, aes(x=Method, y=F1)) + geom_bar(stat="identity", fill="lightblue") + ggtitle("F1 score")
ged_plot <- ggplot(eval_stat, aes(x=Method, y=GED)) + geom_bar(stat="identity", fill="lightblue") + ggtitle("Graph edit distance")

library(gridExtra)
grid.arrange(monocle_plot, tscan_plot, ged_plot, f1_plot, nrow=2)
```

